download: hk_database.csv
	@echo "Downloaded hk_database.csv"

hk_database.csv:
	wget -c https://repositorio-salud.conacyt.mx/jspui/bitstream/1000/296/5/hk_database_17ago2023.zip
	unzip hk_database_17ago2023.zip
	rm hk_database_17ago2023.zip